### ISSUE TITLE
Will it work with apache-airflow 1.10.0

### ISSUE THREAD

**Issue by shweta-code** [teamclairvoyant/airflow-scheduler-failover-controller#10]
I initially adopted this library with airflow 1.7. It worked as expected but we are upgrading airflow to 1.10 version . Not able to install the package as it is asking for 1.7 airflow dependency. Do you plan to upgrade to support apache 1.10 or are there any workarounds? What would be the cleanest way to use it with apache-airflow 1.10?

**Comment by BigBig-joe** [comment]
I am facing the same issue now.  It puzzled me days, and i just tried to modify the require as airflow>=1.10.0, but not work.  If  i remove this requirement, i can install the controller, but can't start it.

**Comment by shweta-code** [comment]
> I am facing the same issue now. It puzzled me days, and i just tried to modify the require as airflow>=1.10.0, but not work. If i remove this requirement, i can install the controller, but can't start it.

Try apache-airflow>=1.10.1
I have checked it is working fine.

**Comment by rssanders3** [comment]
This should be fixed with the PR https://github.com/teamclairvoyant/airflow-scheduler-failover-controller/pull/12 which we created RELEASE 1.0.2 (https://github.com/teamclairvoyant/airflow-scheduler-failover-controller/releases/tag/v1.0.2)
