### ISSUE TITLE
Multiple Email Recievers

### ISSUE THREAD

**Issue by DSwift510** [teamclairvoyant/airflow-scheduler-failover-controller#14]
Hi,

First of all, thank you so much for this program.
I was wondering if it has the capability to notify multiple emails upon failure?

Thanks

**Comment by rssanders3** [comment]
Hello DSwift510,

Internally the Scheduler Failover Controller is using Apache Airflows Email Backend:
https://github.com/apache/airflow/blob/master/airflow/utils/email.py

As a result, you should be able to provide a comma-separated list of the emails you want to email alerts to. This would be added to the `alert_to_email ` field in the configurations.

Let me know if this doesn't work.

Thanks,
Robert Sanders
