### ISSUE TITLE
the default ssh port is not 22,how to configure scheduler_failover_controller to another port??

### ISSUE THREAD

**Issue by Georege** [teamclairvoyant/airflow-scheduler-failover-controller#29]
my system default ssh port is not 22,
how to configure scheduler_failover_controller to another port??

**Comment by rssanders3** [comment]
Hello @Georege, we haven't encountered this requirement so there's currently no configuration to do this. But it can be done with a simple modification of the code that assembles the SSH Command. 

Both here:
https://github.com/teamclairvoyant/airflow-scheduler-failover-controller/blob/a17ba290e9a6e745edb764a8319f3ee8e94acb62/scheduler_failover_controller/command_runner/command_runner.py#L34
and here:
https://github.com/teamclairvoyant/airflow-scheduler-failover-controller/blob/a17ba290e9a6e745edb764a8319f3ee8e94acb62/scheduler_failover_controller/command_runner/command_runner.py#L36

You can update the `command_split` variable to include your desired port:

`command_split = ["ssh", "-p", "26", host, base_command]`

Its on my todo list to at some point come back and allow people to add additional arguments to the SSH through the configurations.
