### ISSUE TITLE
Will it work when I use apache-airflow 1.9.0?

### ISSUE THREAD

**Issue by CodeDogDream** [teamclairvoyant/airflow-scheduler-failover-controller#7]
I just wonder if  it can work,because I am using apache-airflow-1.9.0

**Comment by beaEpoch** [comment]
delete the setup.py file content 'airflow>=1.7.0' or alter to 'apache-airflow>=1.9.0'

**Comment by CodeDogDream** [comment]
> delete the setup.py file content 'airflow>=1.7.0' or alter to 'apache-airflow>=1.9.0'

中国人？

**Comment by BigBig-joe** [comment]
hi guys , i tried modify the requirement to 'airflow>1.10.0' as my airflow version is 1.10.1 .but it seems useless.  have you fixed this issue?

**Comment by CodeDogDream** [comment]
> hi guys , i tried modify the requirement to 'airflow>1.10.0' as my airflow version is 1.10.1 .but it seems useless. have you fixed this issue?

alter  'airflow>=1.7.0'  to 'airflow >= 1.10.0' in setup.py

**Comment by rssanders3** [comment]
This should be fixed with the PR https://github.com/teamclairvoyant/airflow-scheduler-failover-controller/pull/12 which we created RELEASE 1.0.2 (https://github.com/teamclairvoyant/airflow-scheduler-failover-controller/releases/tag/v1.0.2)

**Comment by BigBig-joe** [comment]
> This should be fixed with the PR #12 which we created RELEASE 1.0.2 (https://github.com/teamclairvoyant/airflow-scheduler-failover-controller/releases/tag/v1.0.2)

i tried  1.0.2, and find it not support python 3.  many syntax error.  I tried to correct syntax error, but it just like endless.
